# Generated by Django 3.2.5 on 2021-11-21 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0002_rename_user_like_image_users_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='users_views',
            field=models.ManyToManyField(blank=True, related_name='images_viewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
