# Generated by Django 3.2.5 on 2021-11-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_users_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='users_likes',
            new_name='users_like',
        ),
    ]
